# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6366f813b14cffb3511531046a7dcecc489b829c49d40d14840bb99fe2468f7081fa40fdc2708dbce576e5dc406198479931861ef30c6b70a47e5c82abd8c6d6

test:
  secret_key_base: d6f478e5e73ac8ff76f66c5f82a9002889f3e8309a2b95275d007b50c74eb8d360c5cfd2a5b76df427557e4a8cbc0a67286c0f056565f10448d375bb133dd6c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
